"use client"
import "bootstrap/dist/css/bootstrap.min.css";
import { baselightTheme } from "./utils/theme/DefaultColors";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "../../components/Navbar";


// export const metadata = {
//   title: 'Go-Food',
//   description: 'Generated by Next.js',
// }

export default function Layout({ children }) {
  return (
        <html lang="en">
          <body>
            
        <ThemeProvider theme={baselightTheme}>

          <CssBaseline />
          <Navbar/>
          <main> {children}</main>
         
        </ThemeProvider>
        </body>

        </html>
  
  )
}
